MAINTAINER Selion <selion@googlegroups.com>

USER root

#=========
# Firefox
#=========
RUN apt-get update -qqy \
  && apt-get -qqy --no-install-recommends install \
    firefox \
  && apt-get purge -y --auto-remove wget \
  && rm -rf /var/lib/apt/lists/* /var/cache/apt/* /tmp/*

#========================
# Selenium Configuration
#========================
COPY config.json $SELION_HOME/config.json
RUN chown -R seluser:seluser $SELION_HOME

USER seluser
