MAINTAINER Selion <selion@googlegroups.com>

USER root

#============================================
# Google Chrome
#============================================
# can specify versions by CHROME_VERSION;
#  e.g. google-chrome-stable=53.0.2785.101-1
#       google-chrome-beta=53.0.2785.92-1
#       google-chrome-unstable=54.0.2840.14-1
#       latest (equivalent to google-chrome-stable)
#       google-chrome-beta  (pull latest beta)
#============================================
ARG CHROME_VERSION="google-chrome-stable"
RUN apk add --no-cache --update chromium=53.0.2785.92-r2 chromium-chromedriver=53.0.2785.92-r2 \
  && ln -s /usr/bin/chromium-browser $SELION_HOME/chromium \
  && ln -s /usr/bin/chromedriver $SELION_HOME/chromedriver

RUN  mkdir /tmp/.X11-unix \
  && chmod 1777 /tmp/.X11-unix \
  && chown root /tmp/.X11-unix/

#========================
# Selenium Configuration
#========================
COPY config.json $SELION_HOME/config.json
RUN chown -R seluser:seluser $SELION_HOME

#=================================
# Chrome Launch Script Modication
#=================================
#COPY chrome_launcher.sh /opt/google/chrome/google-chrome
#RUN chmod +x /opt/google/chrome/google-chrome

USER seluser
