MAINTAINER Selion <selion@googlegroups.com>

USER root

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

#==============
# Xvfb
#==============
RUN apt-get update -qqy \
  && apt-get -qqy install xvfb \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/cache/apt/*

#==============================
# Scripts to run Selion Node
#==============================
COPY \
  entry_point.sh \
  functions.sh \
  $SELION_HOME/
RUN chmod +x $SELION_HOME/entry_point.sh

#============================
# Some configuration options
#============================
ENV SCREEN_WIDTH 1360
ENV SCREEN_HEIGHT 1020
ENV SCREEN_DEPTH 24
ENV DISPLAY :99.0

RUN chown -R seluser:seluser $SELION_HOME

USER seluser
