FROM openjdk:8u92-jre-alpine
MAINTAINER Selion <selion@googlegroups.com>

# Builds on docker selenium (https://github.com/SeleniumHQ/docker-selenium) which we customize for SeLion.
# This is copy of selenium base.  Inheriting FROM selenium base didn't allow over-riding some
# choices already made in selenium base. We also build off an alpine base

# This Docker is just a base for the other SeLion docker images.

#==============================
# Switch java to /dev/urandom
#==============================
RUN sed -i 's/securerandom\.source=file:\/dev\/random/securerandom\.source=file:\/dev\/urandom/' ./usr/lib/jvm/java-1.8-openjdk/jre/lib/security/java.security

#===================
# Timezone settings
#===================
ENV TZ "US/Pacific"
RUN apk add --no-cache --update tzdata=2016d-r0 bash=4.3.42-r3 \
 && cp /usr/share/zoneinfo/${TZ} /etc/localtime \
 && echo "${TZ}" > /etc/timezone \
 && apk del --no-cache tzdata

# The Selenium server version (Keep in sync with Selion server)
ENV SELENIUM_VERSION=%SELENIUM_VERSION%
ENV SELENIUM_FIX=%SELENIUM_FIX%

# Selenium base was already using /opt
ENV SELION_HOME /opt/selion

ENV SEL_SERVER https://selenium-release.storage.googleapis.com
ENV REDIRECT_URL https://oss.sonatype.org/service/local/artifact/maven/content
ENV REPO=%REPO%
ENV SELION_GRID_VERSION=%SELION_GRID_VERSION%

#=============================
# Add selion + selenium server
#=============================
RUN apk add --no-cache --update openssl=1.0.2j-r0 \
  && mkdir -p ${SELION_HOME} \
  && wget -q "$REDIRECT_URL?r=$REPO&g=com.paypal.selion&a=SeLion-Grid&c=jar-with-dependencies&v=$SELION_GRID_VERSION" -O $SELION_HOME/SeLion-Grid.jar \
  && wget -q $SEL_SERVER/$SELENIUM_VERSION/selenium-server-standalone-$SELENIUM_VERSION.$SELENIUM_FIX.jar -O $SELION_HOME/selenium-server-standalone.jar

#========================================
# Add normal user
#========================================
RUN adduser -s /bin/bash -D seluser

#=====================================================================
# Add an empty SeLion download.json. The dependencies will be in place
#=====================================================================
COPY download.json $SELION_HOME/config/download.json

RUN chown -R seluser:seluser $SELION_HOME

USER seluser

WORKDIR $SELION_HOME
CMD ["./entry_point.sh"]
